name: Build-AI-MB-3-Final
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build with Buildozer
        uses: ArtemGr/buildozer-action@v1
        with:
          command: |
            buildozer init
            sed -i 's/requirements = python3,kivy/requirements = python3,kivy,plyer/g' buildozer.spec
            sed -i 's/#android.permissions = INTERNET/android.permissions = INTERNET,MODIFY_AUDIO_SETTINGS/g' buildozer.spec
            buildozer android debug
          buildozer_version: master
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: AI-MB-3-Final-APK
          path: bin/*.apk

